services:
    logbook-backend:
        image: ghcr.io/qcoqco/logbook/backend:latest
        container_name: logbook-api
        restart: always
        ports:
            - '8085:8080'
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        env_file:
            - .env
        networks:
            - logbook-network

    logbook-frontend:
        image: ghcr.io/qcoqco/logbook/frontend:latest
        container_name: logbook-web
        restart: always
        ports:
            - '80:80'
        depends_on:
            - logbook-backend
        networks:
            - logbook-network

networks:
    logbook-network:
        driver: bridge
